apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webprotege-srv-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 30Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webprotege-mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 30Gi

